<?php

namespace App\Models\Admin;

use myframework\Model;

class UserGroupModel extends  Model
{

    protected string $tableName = 'user_group';

    public function getById($id)
    {
        $res = parent::getById($id); // TODO: Change the autogenerated stub
        $res2 = $this->db->select('route')->where('user_group_id = ?',[$res->id])->fetchAll('user_group_permission');
        $pages = [];
        foreach ($res2 as $per)
        $pages[] = $per->route;
        $res->pages = $pages;
        return $res;
    }

    public function add($name,$pages):bool{
        $res = $this->app->db->set(['name'=>$name])->insert($this->tableName);
        if($res === false)
            return  false;

        return $this->addPermission($res,$pages);
    }

    public function addPermission($userGroupId,string|array $pages){
        if(!is_array($pages))
            $pages = array($pages);
        foreach ($pages as $page) {
            $res =$this->app->db->set(['user_group_id' => $userGroupId, 'route' =>$page])->insert('user_group_permission');
            if($res === false)
                return false;
        }
        return true;
    }

    public function update($id,$name,$pages){
        $res = $this->app->db->set(['name'=>$name])->where('id = ?',[$id])->update($this->tableName);
        if($res === false)
            return  false;
        $res = $this->db->where('user_group_id = ?',[$id])->delete('user_group_permission');
        if($res === false)
            return  false;
        return $this->addPermission($id,$pages);
    }
}